-- 코드를 작성해주세요
SELECT
    COUNT(*) AS FISH_COUNT,
    N.FISH_NAME AS FISH_NAME 
FROM
    FISH_INFO I
INNER JOIN
    FISH_NAME_INFO N ON N.FISH_TYPE=I.FISH_TYPE
GROUP BY
    I.FISH_TYPE,N.FISH_NAME
ORDER BY
    COUNT(*) DESC