-- DEPT_ID로 테이블 연결
-- DEPT_ID로 그룹핑
-- 평균 연봉 조회

SELECT
    D.DEPT_ID AS DEPT_ID,
    D.DEPT_NAME_EN AS DEPT_NAME_EN,
    ROUND(AVG(E.SAL),0) AS AVG_SAL
FROM
    HR_DEPARTMENT D
INNER JOIN
    HR_EMPLOYEES E ON E.DEPT_ID=D.DEPT_ID
GROUP BY
    D.DEPT_ID
ORDER BY
    AVG(E.SAL) DESC